version: "2"

services:
  nextcloud:
    build: "."
    ports:
      - "127.0.0.1:8080:80"
    links: ["db", "s3"]
    environment:
      DEBUG: "1"
      NEXTCLOUD_DB_TYPE: "mysql"
      NEXTCLOUD_DB_HOST: "db"
      NEXTCLOUD_DB_USER: "nextcloud"
      NEXTCLOUD_DB_PASSWORD: "pass"
      NEXTCLOUD_DB_NAME: "nextcloud"
      NEXTCLOUD_PASSWORD_SALT: "salty"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASS: "pass"
      NEXTCLOUD_MAIL_SENDER_DOMAIN: "example.com"
      NEXTCLOUD_MAIL_SENDER_USER: "foo"
      NEXTCLOUD_SMTP_HOST: "smtp"
      NEXTCLOUD_SMTP_PORT: "1025"
      NEXTCLOUD_SMTP_AUTHN_TYPE: "LOGIN"
      NEXTCLOUD_SMTP_AUTHN_USER: "user"
      NEXTCLOUD_SMTP_AUTHN_PASSWORD: "pass"
      NEXTCLOUD_S3_HOSTNAME: "s3"
      NEXTCLOUD_S3_PORT: "9000"
      NEXTCLOUD_S3_SSL: "0"
      NEXTCLOUD_S3_USE_PATH_STYLE: "1"
      NEXTCLOUD_S3_BUCKET: "nextcloud"
      NEXTCLOUD_S3_ACCESS_KEY: "access"
      NEXTCLOUD_S3_SECRET_KEY: "secretsecret"
      NEXTCLOUD_S3_AUTOCREATE: "1"

  db:
    image: "mysql:5"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "pass"
    volumes:
      - "db:/var/lib/mysql"

  s3:
    image: "minio/minio"
    command: ["server", "/var/minio"]
    environment:
      MINIO_ACCESS_KEY: "access"
      MINIO_SECRET_KEY: "secretsecret"
    volumes:
      - "s3:/var/minio"
    ports:
      - "127.0.0.1:9000:9000"

  smtp:
    image: "djfarrelly/maildev:1.0.0-rc2"
    command:
      - "bin/maildev"
      - "--incoming-user"
      - "user"
      - "--incoming-pass"
      - "pass"
    ports:
      - "127.0.0.1:1080:1080"

volumes:
  db:
  s3:
